const types = {
  REQUEST_PLACES: 'REQUEST_PLACES',
  RECEIVE_PLACES: 'RECEIVE_PLACES',
  INVALIDATE_ADDRESS: 'INVALIDATE_ADDRESS',
  CLOSE_MAP_COLUMN: 'CLOSE_MAP_COLUMN',
  OPEN_MAP_COLUMN: 'OPEN_MAP_COLUMN',
  REQUEST_PLACES_FROM_DB: 'REQUEST_PLACES_FROM_DB',
  SAVE_TO_DB_BEGIN: 'SAVE_TO_DB_BEGIN',
  SAVE_TO_DB_SUCCESS: 'SAVE_TO_DB_SUCCESS',
  SAVE_TO_DB_ERROR: 'SAVE_TO_DB_ERROR'
}

export default types
